# Generated by Django 5.1.7 on 2026-06-25 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=24)),
                ("timeframe", models.CharField(max_length=8)),
                ("price", models.DecimalField(decimal_places=10, max_digits=24)),
                (
                    "ma7",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                (
                    "ma25",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                (
                    "ma99",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                (
                    "delta",
                    models.DecimalField(decimal_places=10, default=0, max_digits=28),
                ),
                (
                    "cvd",
                    models.DecimalField(decimal_places=10, default=0, max_digits=28),
                ),
                (
                    "open_interest",
                    models.DecimalField(decimal_places=10, default=0, max_digits=28),
                ),
                (
                    "open_interest_change_percent",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "funding_rate",
                    models.DecimalField(decimal_places=10, default=0, max_digits=14),
                ),
                (
                    "top_trader_account_ratio",
                    models.DecimalField(decimal_places=8, default=0, max_digits=14),
                ),
                (
                    "top_trader_position_ratio",
                    models.DecimalField(decimal_places=8, default=0, max_digits=14),
                ),
                (
                    "adx",
                    models.DecimalField(decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "atr",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=10, default=0, max_digits=28),
                ),
                (
                    "volume_ma20",
                    models.DecimalField(decimal_places=10, max_digits=28, null=True),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("UP", "Uptrend"),
                            ("DOWN", "Downtrend"),
                            ("SIDEWAYS", "Sideways"),
                        ],
                        default="SIDEWAYS",
                        max_length=12,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=24)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=12,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=24)),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=10, max_digits=24)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=10, default=0, max_digits=24),
                ),
                ("leverage", models.PositiveSmallIntegerField(default=1)),
                ("stop_loss", models.DecimalField(decimal_places=10, max_digits=24)),
                (
                    "take_profit_1",
                    models.DecimalField(decimal_places=10, max_digits=24),
                ),
                (
                    "take_profit_2",
                    models.DecimalField(decimal_places=10, max_digits=24),
                ),
                (
                    "take_profit_3",
                    models.DecimalField(decimal_places=10, max_digits=24),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=10, default=0, max_digits=24),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=10, default=0, max_digits=24),
                ),
                (
                    "pnl_percent",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=10, default=0, max_digits=24),
                ),
                ("open_reason", models.TextField()),
                ("close_reason", models.TextField(blank=True)),
                ("is_paper", models.BooleanField(default=True)),
                ("tp1_hit", models.BooleanField(default=False)),
                ("tp2_hit", models.BooleanField(default=False)),
                ("breakeven_moved", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBinanceCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("api_secret_encrypted", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binance_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingBotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(default="BTCUSDT", max_length=24)),
                ("timeframe_signal", models.CharField(default="15m", max_length=8)),
                ("timeframe_trend", models.CharField(default="1h", max_length=8)),
                ("leverage", models.PositiveSmallIntegerField(default=3)),
                (
                    "margin_type",
                    models.CharField(
                        choices=[("isolated", "Isolated"), ("cross", "Cross")],
                        default="isolated",
                        max_length=12,
                    ),
                ),
                (
                    "risk_per_trade_percent",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "max_daily_loss_percent",
                    models.DecimalField(decimal_places=2, default=3, max_digits=5),
                ),
                ("max_open_positions", models.PositiveSmallIntegerField(default=1)),
                (
                    "adx_min",
                    models.DecimalField(decimal_places=2, default=20, max_digits=6),
                ),
                (
                    "atr_multiplier_sl",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=6),
                ),
                (
                    "atr_multiplier_tp",
                    models.DecimalField(decimal_places=2, default=3, max_digits=6),
                ),
                ("use_trailing_stop", models.BooleanField(default=True)),
                (
                    "trailing_atr_multiplier",
                    models.DecimalField(decimal_places=2, default=1.2, max_digits=6),
                ),
                ("enable_long", models.BooleanField(default=True)),
                ("enable_short", models.BooleanField(default=True)),
                ("is_running", models.BooleanField(default=False)),
                ("live_mode_requested", models.BooleanField(default=False)),
                (
                    "paper_balance",
                    models.DecimalField(decimal_places=8, default=10000, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "symbol"), name="unique_user_symbol_config"
                    )
                ],
            },
        ),
    ]
