# Generated by Django 5.1.7 on 2026-07-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_rescale_entry_score_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingbotconfig',
            name='top_mover_side',
            field=models.CharField(blank=True, choices=[('gainer', 'Long (top gainer)'), ('loser', 'Short (top loser)')], help_text='Which top-movers side (gainer/long or loser/short) this coin was registered from. Null for manually added coins.', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='adx_tp_high_threshold',
            field=models.PositiveSmallIntegerField(default=0, help_text='When ADX ≥ this, widen TP R-multiple by 33%. 0 = disabled.'),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='adx_tp_low_threshold',
            field=models.PositiveSmallIntegerField(default=0, help_text='When ADX ≤ this, narrow TP R-multiple by 33%. 0 = disabled.'),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='ma_slope_min_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Minimum MA7 slope (% change per candle over 5 bars) in signal direction. 0 = disabled.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='partial_entry_size_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Percentage of planned quantity to enter initially (e.g. 50 = half size). Rest added on confirmation.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='require_confirmed_higher_tf',
            field=models.BooleanField(default=False, help_text='Require higher TF to be CONFIRMED_UPTREND/DOWNTREND (not weak/early). Blocks entries on weak trends.'),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='volume_spike_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Require signal candle volume >= N × volume MA20 (e.g. 2.0). 0 = disabled.', max_digits=4),
        ),
    ]
