# Generated by Django 5.1.7 on 2026-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_tp3_trailing_default_3_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingbotconfig',
            name='daily_loss_limit_enabled',
            field=models.BooleanField(default=True, help_text="Block new entries once today's realized loss reaches max_daily_loss_percent of paper balance."),
        ),
    ]
