# Generated by Django 5.1.7 on 2026-08-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_daily_loss_limit_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscordalertconfig',
            name='notify_scanner_changes',
            field=models.BooleanField(default=True),
        ),
    ]
