# Generated by Django 6.1.1 on 2026-09-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0036_extended_move_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='auto_suppress_losing_symbols',
            field=models.BooleanField(default=False, help_text="Block entries on this symbol when its last 20+ closed trades have <40% win rate. Account-wide: applies to every scanner coin, kept in sync across all of a user's configs."),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='auto_suppress_losing_tags',
            field=models.BooleanField(default=True, help_text="Block entries when a setup tag has <40% win rate over 20+ recent trades. Account-wide: applies to every scanner coin, kept in sync across all of a user's configs."),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='confidence_leverage_enabled',
            field=models.BooleanField(default=True, help_text="Account-wide: applies to every scanner coin, kept in sync across all of a user's configs."),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='live_mode_requested',
            field=models.BooleanField(default=False, help_text="Account-wide: applies to every scanner coin, kept in sync across all of a user's configs."),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='max_open_positions',
            field=models.PositiveSmallIntegerField(default=5, help_text="Account-wide: applies to every scanner coin, kept in sync across all of a user's configs."),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='min_effective_leverage',
            field=models.PositiveSmallIntegerField(default=0, help_text="Minimum leverage when confidence scaling is active. 0 = no floor (allow full scaling). Account-wide: applies to every scanner coin, kept in sync across all of a user's configs."),
        ),
        migrations.AlterField(
            model_name='tradingbotconfig',
            name='position_margin_usdt',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Fixed margin allocated to each new position. Null uses risk-based sizing. Account-wide: applies to every scanner coin, kept in sync across all of a user's configs.", max_digits=20, null=True),
        ),
    ]
