# Generated by Django 6.1.1 on 2026-09-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0038_add_coin_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingbotconfig',
            name='admin_mirrored',
            field=models.BooleanField(default=False, help_text='True if this config was auto-created for a regular user because an admin has this coin (eligible for removal once no admin has it anymore). Never set on a coin the user added themselves.'),
        ),
    ]
