# Generated by Django 6.1.1 on 2026-09-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0039_add_admin_mirrored_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('delta', models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ('cvd', models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ('open_interest', models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ('open_interest_change_percent', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('funding_rate', models.DecimalField(decimal_places=10, default=0, max_digits=14)),
                ('top_trader_account_ratio', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('top_trader_position_ratio', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('volume', models.DecimalField(decimal_places=10, default=0, max_digits=28)),
                ('volume_ma20', models.DecimalField(decimal_places=10, max_digits=28, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trading.trade')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
