# Generated by Django 6.1.1 on 2026-09-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_add_trade_snapshot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketsnapshot',
            index=models.Index(fields=['symbol', 'timeframe', '-created_at'], name='trading_snap_sym_tf_idx'),
        ),
    ]
