# Generated by Django 6.1.1 on 2026-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_marketsnapshot_trading_snap_sym_tf_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlog',
            name='category',
            field=models.CharField(choices=[('TRADE', 'Trade'), ('SCANNER', 'Scanner'), ('SYSTEM', 'System')], default='SYSTEM', max_length=12),
        ),
    ]
