# Generated by Django 6.1.1 on 2026-09-29 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0044_short_only_entry_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='mae_pct',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='mae_r',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='mfe_pct',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='mfe_r',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='r_multiple',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='SignalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=24)),
                ('side', models.CharField(max_length=8)),
                ('result', models.CharField(max_length=40)),
                ('is_paper', models.BooleanField(default=True)),
                ('score', models.SmallIntegerField(default=0)),
                ('confidence', models.SmallIntegerField(default=0)),
                ('grade', models.CharField(blank=True, default='', max_length=2)),
                ('regime', models.CharField(blank=True, default='', max_length=24)),
                ('setup_tags', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('ref_stop', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('ref_tp1', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('levels_source', models.CharField(default='none', max_length=12)),
                ('signal_candle_ts', models.BigIntegerField(default=0)),
                ('outcome_1h', models.JSONField(blank=True, default=dict)),
                ('outcome_4h', models.JSONField(blank=True, default=dict)),
                ('outcome_24h', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trading.tradingbotconfig')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='trading.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='sigdec_user_created_idx'), models.Index(fields=['user', 'result', '-created_at'], name='sigdec_user_result_idx')],
                'constraints': [models.UniqueConstraint(fields=('config', 'side', 'result', 'signal_candle_ts'), name='signal_decision_dedupe_uniq')],
            },
        ),
    ]
